### ISSUE TITLE
Import error for opticspy.ray_tracing

### ISSUE THREAD

**Issue by atelierhide** [Sterncat/opticspy#5]
`from opticspy.ray_tracing import *` gives the following error:

```
opticspy/ray_tracing/__init__.py in <module>()
----> 1 import lens, trace, glass, draw, analysis, field, codev

ImportError: No module named glass
```

**Comment by Sterncat** [comment]
Try change it to glass_function and put you test file in the same folder as opticspy. 
Or I highly recommend you for now just download the opticspy from github, and import it in the path same as this folder.
I am really sorry I am still testing the relative import thing and if the release version is usable for real ray tracing part. But I am also really happy because you are the first user for real ray tracing part.

**Comment by atelierhide** [comment]
The release version with revised `ray_tracing/__init__.py` works fine for the triplet and double-gauss examples. Also, the `codev.readseq` looks quite useful. Thanks for sharing this project and looking forward to your progress.

**Comment by Sterncat** [comment]
Great! I am glad the project helps you!
